### ISSUE TITLE
Dependencies are not available

### ISSUE THREAD

**Issue by abhilashdasari** [harshsharma-cb/FASE#2]
dependencies ‘BioPhysConnectoR’, ‘survivalAnalysis’ are not available for package ‘FASE’

**Comment by harshsharma-cb** [comment]
You can try this:
1. install.packages("BioPhysConnectoR", dependencies=TRUE, repos ="https://cran-archive.r-project.org/")

2. install.packages("survivalAnalysis", dependencies=TRUE, repos ="https://cran-archive.r-project.org/")

OR

1. Download the source package for BioPhysConnectoR from: http://download.nust.na/pub3/cran/src/contrib/Archive/BioPhysConnectoR/ and install it as: install.packages("path to downloaded package", repos = NULL, type = "source")

2. devtools::install_bitbucket("mwiesweg/survivalAnalysis")

**Comment by abhilashdasari** [comment]
Thanks for your quick response.
